all: build

run:
	./main

build:
	yacc -d -Wcounterexamples parser.y
	flex lex.l
	gcc main.c decl.c printer.c adder.c lex.yy.c y.tab.c -o main

clean:
	rm -f lex.yy.c main parser.tab.c parser.tab.h y.tab.c y.tab.h

.PHONY:	clean
